on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
      with:
         path: './src/github.com/kevinburke/logrole'
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "GO111MODULE=off" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
    - name: Download dependencies
      run: go get -t -v ./...
      working-directory: './src/github.com/kevinburke/logrole'
    - name: Run tests
      run: make ci
      working-directory: './src/github.com/kevinburke/logrole'
